### ISSUE TITLE
你好 有QQ或者其他联系方式吗？ 这个SQL能提供给我一份吗？ 谢谢

### ISSUE THREAD

**Issue by xun6626125** [achievejia/springboot_saas#1]
如题，我的QQ 309666726

**Comment by achievejia** [comment]
https://blog.csdn.net/fegda/article/details/106213008  此文章中已经提供SQL语句

**Comment by achievejia** [comment]
> 如题，我的QQ 309666726

https://blog.csdn.net/fegda/article/details/106213008
