### ISSUE TITLE
前辈，new的DataSource对象中没有pool对象，导致读取dataSource的时候是null。用你的demo跑也是一样无法获取到，能解答下吗？

### ISSUE THREAD

**Issue by guodastanson** [achievejia/springboot_saas#2]
HikariDataSoure(HikariPool-1) 这是正常的从config里加载的master数据源
HikariDataSoure(null)这是其他通过new或者Builder创建的数据源。
这个直接导致determineTargetDataSource时从Map中get出来的DataSource对象是null

**Comment by achievejia** [comment]
把你的代码贴出来
